#!/bin/bash
set -e

# Activate virtual environment
source .venv/bin/activate

# Generate LD_LIBRARY_PATH
# This script mimics the logic in scripts/train.sh to find library paths
LD_LIB_PATH=$(python -c "
import os
import nvidia.cudnn
import nvidia.cublas
import nvidia.cuda_nvcc
import nvidia.cuda_runtime
import nvidia.cuda_nvrtc
import nvidia.cufft
import nvidia.cusolver
import nvidia.cuda_cupti
import nvidia.nccl
import nvidia.cusparse

libs = [
    nvidia.cudnn,
    nvidia.cublas,
    nvidia.cuda_nvcc,
    nvidia.cuda_runtime,
    nvidia.cuda_nvrtc,
    nvidia.cufft,
    nvidia.cusolver,
    nvidia.cuda_cupti,
    nvidia.nccl,
    nvidia.cusparse
]

paths = [lib.__path__[0] + '/lib' for lib in libs]
# Join with colon
print(':'.join(paths))
")

# Write to .env file
echo "# Generated by scripts/generate_vscode_env.sh" > .env
echo "LD_LIBRARY_PATH=$LD_LIB_PATH" >> .env
echo "XLA_PYTHON_CLIENT_PREALLOCATE=false" >> .env
echo "XLA_PYTHON_CLIENT_ALLOCATOR=platform" >> .env
echo "RAYON_NUM_THREADS=8" >> .env
echo "TPU_RUNTIME_METRICS_PORTS=8431,8432,8433,8434" >> .env

echo "Generated .env with LD_LIBRARY_PATH and other variables."
